name: Workflow for testers  with GitHub Actions

on:
  release:
    types: [published]
  workflow_dispatch: # Trigger the workflow manually

env:
  # These secret keys must be created in the GitHub repository
  # Go to your GitHub repository → Settings → Secrets and Variables → Actions → New Repository Secret
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.action}}/cimath_docker_image:latest

jobs:
  Deploy:
    name: Delivery docker image to Container registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Mise à jour de la version

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: npm run build

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Extract metadata for docker
        id: meta
        uses: docker/login-action@v3
        with:
          images: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}

      - name: Publish
        run: docker build . --tag ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
          docker push ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
