name: workflow for CI with github actions

on:
  push:
    branches:
      - master

env:
  baseUrl: http://localhost:3000

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: build project
        run: npm run build

      - name: checkout Typescript Errors
        run: npm i -g typescript && tsc

      - name: checkout Eslint Error
        run: npm run Eslint
