name: workflow for CI with github actions

on:
  push:
    branches:
      - master

env:
  baseUrl: http://localhost:3000

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Checkout TypeScript Errors
        run: yarn add typescript && tsc

      - name: Checkout ESLint Errors
        run: yarn lint

      - name: Launch Unit Test & Integration Test
        run: yarn test

      - name: Save build data
        uses: actions/upload-artifact@v4
        with:
          name: build
          if-no-files-found: Error
          path: .next

  run-cypress-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/Checkout@v4

      - name: Download the build data
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .next

      - name: Cypress run test
        uses: Cypress-io/github-action@v6
        with:
          run: yarn start
          path: chrome
