name: Workflow for CI with GitHub Actions

on:
  push:
    branches:
      - master

env:
  baseUrl: http://localhost:3000

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Enable Corepack
        run: corepack enable

      - name: Set Yarn to the required version
        run: corepack prepare yarn@4.7.0 --activate

      - name: Install Vercel globally
        run: yarn global add vercel@latest

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install
