name: Vercel Deployment (Yarn Version Fix)

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  NODE_VERSION: 20.x
  YARN_VERSION: 4.7.0 # Doit correspondre exactement à package.json

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # Étape cruciale: Configuration initiale de Corepack
      - name: Initialize Corepack
        run: |
          # Force l'activation de Corepack
          corepack enable --install-directory=/usr/local/bin
          corepack prepare yarn@${{ env.YARN_VERSION }} --activate
          corepack prepare pnpm@latest --activate  # Optionnel

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
          always-auth: false

      # Vérification explicite de l'environnement
      - name: Verify Yarn Version
        run: |
          echo "Node version: $(node --version)"
          echo "Yarn version: $(yarn --version)"
          echo "Yarn path: $(which yarn)"
          [ "$(yarn --version)" = "${{ env.YARN_VERSION }}" ] || exit 1

      - name: Install dependencies
        run: |
          yarn config set --home enableTelemetry 0
          yarn install --immutable --inline-builds
        env:
          YARN_ENABLE_GLOBAL_CACHE: 1
          YARN_CACHE_FOLDER: .yarn/cache

      - name: Build project
        run: yarn build

      - name: Deploy to Vercel
        run: |
          vercel pull --yes --token=${{ env.VERCEL_TOKEN }}
          vercel deploy --prod --token=${{ env.VERCEL_TOKEN }}
