name: Vercel CD Deployment

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  NODE_VERSION: 20.x
  YARN_VERSION: 4.7.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # Augmentez si nécessaire

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn" # Cache automatique pour Yarn

      - name: Setup Yarn
        run: |
          corepack enable
          corepack prepare yarn@${{ env.YARN_VERSION }} --activate

      - name: Install dependencies (with cache)
        run: |
          yarn config set nodeLinker node-modules  # Désactive PnP si problématique
          yarn install --immutable --check-cache

      - name: Skip Cypress install (si non nécessaire)
        run: |
          echo "CYPRESS_INSTALL_BINARY=0" >> .env
          echo "SKIP_CYPRESS_INSTALL=true" >> .env

      - name: Build project
        run: yarn build

      - name: Deploy to Vercel
        run: |
          vercel pull --yes --token=${{ env.VERCEL_TOKEN }}
          vercel deploy --prod --token=${{ env.VERCEL_TOKEN }}
